// ============================================
// WORLD CLOCK — Data Landmark Kota
// ============================================

const LANDMARKS = {
  jakarta:    'Monas · Kota Tua · Ancol',
  singapore:  'Marina Bay · Orchard · Sentosa',
  tokyo:      'Shibuya · Shinjuku · Akihabara',
  london:     'Big Ben · Tower Bridge · Camden',
  newyork:    'Times Square · Central Park · Brooklyn',
  paris:      'Eiffel · Louvre · Montmartre',
  dubai:      'Burj Khalifa · Palm · Marina',
  sydney:     'Opera House · Bondi · Darling Harbour',
  seoul:      'Gangnam · Hongdae · Myeongdong',
  beijing:    'Forbidden City · Great Wall · Wangfujing',
  bangkok:    'Grand Palace · Khao San · Chatuchak',
  makassar:   'Pantai Losari · Benteng Rotterdam',
  jayapura:   'Danau Sentani · Pantai Base G',
  colombo:    'Galle Face · Fort · Pettah',
  kualalumpur:'Petronas · Bukit Bintang · Batu Caves',
  mumbai:     'Gateway of India · Marine Drive',
  hongkong:   'Victoria Peak · Tsim Sha Tsui',
  losangeles:'Hollywood · Santa Monica · Venice',
  saopaulo:   'Ibirapuera · Paulista · Vila Madalena',
  cairo:      'Pyramids · Nile · Khan el-Khalili',
  istanbul:   'Hagia Sophia · Blue Mosque · Bosphorus',
  moscow:     'Red Square · Kremlin · Bolshoi',
  berlin:     'Brandenburg · Checkpoint Charlie',
  rome:       'Colosseum · Vatican · Trevi',
  madrid:     'Prado · Retiro · Gran Vía',
  amsterdam:  'Anne Frank · Vondelpark · Jordaan',
  zurich:     'Lake Zurich · Old Town · Bahnhofstrasse',
  stockholm:  'Gamla Stan · Vasa · Djurgården',
  athens:     'Acropolis · Plaka · Syntagma',
  lisbon:     'Belém · Alfama · Tram 28',
  toronto:    'CN Tower · Distillery · Kensington',
  vancouver:  'Stanley Park · Granville · Gastown',
  mexicocity: 'Zócalo · Chapultepec · Coyoacán',
  buenosaires:'La Boca · Palermo · Recoleta',
  lima:       'Miraflores · Barranco · Plaza Mayor',
  bogota:     'La Candelaria · Monserrate',
  santiago:   'San Cristóbal · Bellavista · Centro',
  auckland:   'Sky Tower · Viaduct · Mission Bay',
  suva:       'Nadi · Coral Coast · Pacific Harbour',
  melbourne:  'Federation Square · St Kilda',
  perth:      'Kings Park · Cottesloe · Fremantle',
  johannesburg:'Apartheid Museum · Maboneng',
  lagos:      'Lekki · Victoria Island · Nike Art',
  nairobi:    'Maasai Market · Nairobi Park',
  casablanca: 'Hassan II · Medina · Corniche',
  addisababa: 'Meskel Square · Entoto · Merkato',
  tehran:     'Milad Tower · Grand Bazaar',
  riyadh:     'Kingdom Centre · Diriyah',
  dhaka:      'Lalbagh · Ahsan Manzil · Sadarghat',
  kathmandu:  'Boudhanath · Swayambhu · Thamel',
  newdelhi:   'Red Fort · Qutub Minar · India Gate',
  hanoi:      'Hoan Kiem · Old Quarter · Temple',
  manila:     'Intramuros · Makati · BGC',
};

function getLandmark(cityId) {
  return LANDMARKS[cityId] || 'Kawasan pusat kota · Landmark ikonik';
}
